const FALLBACK_DEVELOPER_PLACEHOLDER_QUOTE = 'Works on my machine is a deployment strategy.'

export const DEVELOPER_PLACEHOLDER_QUOTES = [
  'Works on my machine is a deployment strategy.',
  'I fixed a bug by deleting the feature.',
  'There is no place like 127.0.0.1.',
  'I dream in stack traces.',
  'Ship it now, debug it in production.',
  'Semicolons are tiny trust exercises.',
  'My code has no bugs, only undocumented features.',
  'I renamed the variable and fixed three mysteries.',
  'Keyboard not found, press F1 to continue coding.',
  'Git blame is my time machine.',
  'I wrote clean code once, then requirements changed.',
  "The cache is always warm on someone else's laptop.",
  'I do not always test, but when I do, it is in prod.',
  'If it compiles, it is probably still broken.',
  'JavaScript: now with 20 ways to sort one array.',
  'Regex is just line noise with confidence.',
  'I made it faster by turning off logging and hope.',
  'TODO is a love letter to future me.',
  'Future me is filing a bug against past me.',
  'The only constant is changing API contracts.',
  'My branch name is longer than the fix.',
  'I optimize after coffee and before regret.',
  'Unit tests are just tiny panic attacks.',
  'I chased a race condition and lost the race.',
  'NPM installed 900 packages to print hello.',
  'I can explain this code, just not right now.',
  'Merge conflict is pair programming with your past.',
  'CI failed because it sensed fear.',
  'My favorite design pattern is copy and adapt.',
  'I refactored and discovered archaeology.',
  'Documentation is fiction until proven current.',
  'This endpoint is stable except on weekdays.',
  'I have a PhD in restarting servers.',
  'One more quick fix is how legends begin.',
  'Dark mode is my production incident blanket.',
  'I log therefore I am.',
  'Exceptions are just surprise tutorials.',
  'Feature complete means bugs are now user facing.',
  'I trust types, but I still console.log.',
  'My pull request is small if you squint.',
  'Broken builds build character.',
  'The sprint is short, the backlog is forever.',
  'I use tabs for speed and spaces for peace talks.',
  'Every hotfix starts with maybe one line.',
  'I did not choose the tech debt life.',
  'Code review: where optimism meets edge cases.',
  'This architecture is future proof until lunch.',
  'My debugger and I are in a committed relationship.',
  'Ship small, panic smaller.',
  'Rate limits are just API cardio.',
  'YAML is whitespace with authority.',
  'I promise this is the final final final commit.',
  'Bug reproduced, coffee consumed, bug vanished.',
  'I write comments for the version of me without sleep.',
  'The build passed, suspiciously.',
  'I automate everything except naming things.',
  'My favorite framework is whichever already works.',
  'Story points are estimates, not prophecies.',
  'The function is pure, my intentions are not.',
  'I made it generic and lost everyone.',
  'Legacy code is code that survived.',
  'I open one terminal and summon seven.',
  'If in doubt, clear cache and deny everything.',
  'The rollback plan is confidence and git tags.',
  'I removed dead code and three dependencies screamed.',
  'This script has one job and six side quests.',
  'Scope creep entered the chat.',
  'I thought it was DNS, and it was DNS.',
  'Compile time is where patience goes to benchmark.',
  'My API is RESTful-ish.',
  'I came for the bug and stayed for the mystery.',
  'Naming things is the final boss.',
  'I closed the issue by opening two more.',
  'It worked yesterday, so today is advanced mode.',
  'The status page is my weather report.',
  'I write resilient code and fragile assumptions.',
  'This migration is reversible in theory.',
  'If this fails, blame timezone math.',
  'I touched one file and 42 tests cried.',
  'Production is the best teacher and the worst grader.',
  'I benchmarked it once and printed the graph.',
  'The code is self documenting if you are psychic.',
  'I kept it simple and complexity filed an appeal.',
  'Refactor Friday, rollback Monday.',
  'I lint therefore I ship.',
  'My temporary workaround now has birthdays.',
  'That warning is decorative.',
  'It is not flaky, it is probabilistic.',
  'I only added one line and seven packages.',
  'This bug only appears during demos.',
  'I have strong opinions, weakly typed.',
  'The service is stateless, my state is not.',
  'Green tests, red face.',
  'I mocked the API and it mocked me back.',
  'There are two hard things: naming, cache, and off by one.',
  'I started with a script and ended with a platform.',
  'My favorite cloud region is localhost.',
  'We will scale when optimism runs out.',
  'I wrote a quick query and met the whole database.',
  'Done means deployed, monitored, and still calm.'
] as const

export function pickRandomDeveloperPlaceholderQuote(): string {
  if (DEVELOPER_PLACEHOLDER_QUOTES.length === 0) {
    return FALLBACK_DEVELOPER_PLACEHOLDER_QUOTE
  }

  const index = Math.floor(Math.random() * DEVELOPER_PLACEHOLDER_QUOTES.length)
  return DEVELOPER_PLACEHOLDER_QUOTES[index] || FALLBACK_DEVELOPER_PLACEHOLDER_QUOTE
}
